### ISSUE TITLE
Suggestion for next release...

### ISSUE THREAD

**Issue by AlandEr2612** [afollestad/app-theme-engine#10]
Not to sound obsessive, but the widget switch is missing on the ATE default views, and the text of EditText, checkbox and radio button are always black, because Text Colors tags dont work, it would be great to be able to change the color of these texts do not? ... I know that means more code and computation time, but an attempt would not be bad...

**Comment by afollestad** [comment]
There isn't anything preventing that from working. The default widgets do not currently set the text color tags.

**Comment by AlandEr2612** [comment]
ATESwitch i think that is missing...

**Comment by AnimbusDev** [comment]
@afollestad Yeah, I'm pretty sure ATE switch is missing as said above

**Comment by afollestad** [comment]
Added `ATESwitch` (which exends `SwitchCompat`, not `Switch`), along with tinting support for `Switch` (on API 16+) and `SwitchCompat` (on all API levels).
