### ISSUE TITLE
preApply() doesnt work.

### ISSUE THREAD

**Issue by adeldolgov** [afollestad/app-theme-engine#105]
Hello!
Today i updated your library to version 1.0.0 and now i cant apply config.
When i write .postApply or .apply(this) <after ATE.config method> it throws 
"Caused by: java.lang.IllegalStateException: A factory has already been set on this LayoutInflater."

**Comment by julianostarek** [comment]
@adeldolgov Because both methods were deprecated with 1.0.0. In Android Studio, right click -> go to declaration and you'd see it.

**Comment by adeldolgov** [comment]
Well,so how i can apply now?

**Comment by adeldolgov** [comment]
@julianostarek I didnt find any another method for apply config.

**Comment by afollestad** [comment]
@adeldolgov look at the sample project and documentation (in the README)

**Comment by adeldolgov** [comment]
@afollestad I readed the documentation and looked sample project, in documentation, the config method have .apply(this) at the end.
In my application it throws this exception.

**Comment by adeldolgov** [comment]
@afollestad I'll be very grateful if You say me how to do this. I spent 4 hours and didnt find solution :(

**Comment by adeldolgov** [comment]
@afollestad Do i need to write correct methods (preApply,postApply,etc.) and when i select new color,i should write .commit() and then recreate activity?

**Comment by julianostarek** [comment]
@adeldolgov with 1.0.0, theming is done at inflation time, you shouldn't need to do anything

**Comment by adeldolgov** [comment]
@julianostarek I'm afraid to seem bothersome,but what you mean? And can you send example code to me?

**Comment by adeldolgov** [comment]
@julianostarek I should write commit of theme before 
ATE.preApply(this, getATEKey());
        super.onCreate(savedInstanceState);
?
