### ISSUE TITLE
Tags Dont Work Well

### ISSUE THREAD

**Issue by AlandEr2612** [afollestad/app-theme-engine#11]
The tag text_shadow_primary_color dont change the shadow color... 

i have this but dont work...

<TextView
            android:id="@+id/tv_app_name"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:gravity="center"
            android:shadowColor="@color/colorPrimary"
            android:shadowDx="2.5"
            android:shadowDy="2.5"
            android:shadowRadius="5"
            android:tag="text_primary_color_dark,text_shadow_primary_color"
            android:text="@string/app_name"
            android:textSize="75sp" /> 

and bg_tint_accent_color.. i have this... 

<android.support.design.widget.FloatingActionButton
                android:id="@+id/fab_fingerprint"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:tag="bg_tint_accent_color" />

and dont work too... :/ ...

KEY_BG_TINT_PRIMARY_COLOR_DARK:
                TintHelper.setTintAuto(current, Config.primaryColorDark(context, key), true);

you have to make a tint method specific for the Floating action button... i guess... and i dont know why the sahdow dont change if the code is right...

**Comment by AlandEr2612** [comment]
this is how i save my theme...

public static void saveTheme(AppCompatActivity activity, Integer color) {
        Config config = ATE.config(activity, null);
        config.primaryColor(color);
        config.autoGeneratePrimaryDark(true);
        config.accentColor(CircleView.shiftColorDown(color));
        config.coloredStatusBar(true);
        config.coloredNavigationBar(true);
        config.commit();
        activity.recreate();
    }

**Comment by AnimbusDev** [comment]
@Alander2612 because he didn't release the new version with those tags version yet...

**Comment by AnimbusDev** [comment]
@Alander2612 you can also replace the Config.commit; activity.recreate; with Config.apply(activity)

**Comment by afollestad** [comment]
@AlandEr2612 also, you should really use Markdown's code formatting. Not doing so leaves parts out in your comment and makes it hard to read them.

**Comment by afollestad** [comment]
Updated both of your comments for syntax highlighting in case you're curious on how it's done.

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.4.0
