### ISSUE TITLE
RecyclerView Edge Scroll

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#12]
The overscroll tinting doesn't work in the sample

**Comment by afollestad** [comment]
It was working before I published the new release.

I'm not at a computer right now to debug it though, since it's Christmas.

On Thu, Dec 24, 2015, 3:45 PM AnimbusDev <notifications@github.com> wrote:

> The overscroll tinting doesn't work in the sample
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/app-theme-engine/issues/12>.
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Comment by afollestad** [comment]
It's working for me in the sample:

![screener_20151224 17-14-00](https://cloud.githubusercontent.com/assets/1820165/11998373/d9b8e134-aa61-11e5-82b6-62663c36204e.png)
