### ISSUE TITLE
Tinting widgets in the overflow menu

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#14]
Widgets in some menus aren't themed

https://goo.gl/photos/JACWjyFYYMsWDTDV6

**Comment by kabouzeid** [comment]
Can confirm

**Comment by afollestad** [comment]
Yeah, it happens in the sample. I haven't gotten around to figuring it out and won't have time to do so until next week.

**Comment by afollestad** [comment]
The main reason is that `onMenuOpened()` of `Activity` currently isn't called in `MainActivity` for whatever reason, it had been originally and stopped working recently.

**Comment by afollestad** [comment]
So, @plusCubed got it working in the deep sub menus. All that we have left to fix now is the initial overflow menu.

**Comment by afollestad** [comment]
Fixed in both the overflow and submenus now.
