### ISSUE TITLE
RecyclerView overscroll color SOMETIMES not working

### ISSUE THREAD

**Issue by kabouzeid** [afollestad/app-theme-engine#15]
![screenshot_20151225-115823](https://cloud.githubusercontent.com/assets/7303830/12002476/5d0b313e-aaff-11e5-97d2-7e5525ff1fa8.png)

**Comment by AnimbusDev** [comment]
It's pretty spotty in the sample. If you restart the sample it might start working

**Comment by afollestad** [comment]
I might need help debugging this one since I can't reproduce it. 

![screener_20151225 11 05 10](https://cloud.githubusercontent.com/assets/1820165/12003882/7096aff6-aaf7-11e5-8807-378bc1a640d2.png)

**Comment by PDDStudio** [comment]
I've the same issue in the sample at OP. Just let me know how I/we can help to get this fixed.
@afollestad you might want to have a look at this one (in case you got it different)
https://gist.github.com/PDDStudio/caadc623be2b6d9af114

**Comment by kabouzeid** [comment]
@afollestad I tried again and figured out that tinting fails for me as soon as I change something in the theme (dark/light, primary, secondary color etc.)

**Comment by afollestad** [comment]
@PDDStudio I actually found that code on a StackOverflow post and modified it, since using static variables like that here is a bad idea.

@kabouzeid that's helpful, I'll try to reproduce it, thanks

**Comment by afollestad** [comment]
Plus RecyclerView has changed since that code was written. There are 4 edges on RecyclerViews since some scroll horizontally, and the field names changed.

**Comment by afollestad** [comment]
Fixed
