### ISSUE TITLE
AppBarLayout support?

### ISSUE THREAD

**Issue by PDDStudio** [afollestad/app-theme-engine#16]
Using `coloredActionbar(true)` within an AppBarLayout colors the ActionBar - even when not collapsed.

**Comment by afollestad** [comment]
@PDDStudio if you're using an `AppBarLayout`, there shouldn't be a Support Action Bar, right? So it should only color the Toolbar which is inside of it. 

I haven't used an `AppBarLayout` before, where does the coloring actually get applied?

**Comment by afollestad** [comment]
If it gets applied to the Toolbar inside of it, it should already work fine

**Comment by PDDStudio** [comment]
I've a Toolbar inside my ActionBarLayout. But I'm manually applying my theme on every start ( and also call coloredStatusBar(true) ) of my application which ends up that the action bar is themed even when the CollapsingToolbarLayout isn't collapsed

**Comment by afollestad** [comment]
By action bar, you mean an actionbar/toolbar other than the one inside of your `AppBarLayout`?

**Comment by PDDStudio** [comment]
I'm talking about the one inside my AppBarLayout. The setup is like following:
`<AppBarLayout>
<CollapsingToolbarLayout>
<ImageView />
<Toolbar />
<CollapsingToolbarLayout>
<AppBarLayout>`

**Comment by afollestad** [comment]
@PDDStudio I don't see why it wouldn't already work with that, since it should only be coloring the Toolbar inside of your layout.

**Comment by afollestad** [comment]
Unless the `CollapsingToolbarLayout` should be colored instead of the `Toolbar`. Surprisingly, I haven't dealt with these components too much yet so I'm not super familiar with them.

**Comment by AnimbusDev** [comment]
@afollestad
I have the same issue. Check your Google plus.

**Comment by afollestad** [comment]
I had already starting implementing support 😀

It's almost done now

**Comment by afollestad** [comment]
A lot of progress has been made in https://github.com/afollestad/app-theme-engine/commit/3468cf3bbbb044bb816acc2ed6ed5691f5e717b8, it's not 100% done yet

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.6.0
