### ISSUE TITLE
Tab layout support

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#17]
Can you theme TabLayout like NavigationView? Except please give us an option to replace the accent color with the primary text color pertaining to the primarycolor.

For example, you can use the accent color or this:
if the color is dark, then use a light color, and vice versa

**Comment by afollestad** [comment]
Good idea! 

Do you think I should make tag values for this? I want to avoid adding too many tags that will make the library confusing in the end.

**Comment by afollestad** [comment]
Added, haven't documented it yet, but see the sample project.

**Comment by AnimbusDev** [comment]
@afollestad Great work!

Can you please add support for icon tabs? Basically works the same way you did the text (getting the color then changing alpha) but with a ColorStateList and a drawable. Thanks

**Comment by afollestad** [comment]
Added that too, it will match the indicator color (and it will be semi-transparent when not selected)

**Comment by afollestad** [comment]
This is in https://github.com/afollestad/app-theme-engine/commit/833ffda3ad96474e1293083b01d91cef41fab197 and https://github.com/afollestad/app-theme-engine/commit/9c7ca19bec2817eb8f1285e1bb1265f9191c0a81, I also documented the tags (which aren't needed to use default black or white colors).

**Comment by AnimbusDev** [comment]
@afollesrad so if I want the tab's text and indicator colors to match the background (if the background is dark, use light text/icons/indicators, and vice versa) I don't need tags. Is that correct?

**Comment by AnimbusDev** [comment]
@afollestad Just took a look at the code. One thing though, I currently to set the background of the tabs to transparent and it gets its background from the AppBarLayout. I can fix that easily though, but I think it would be easier for developers to not add tags and just have the library get the color from appbarlayout (though thisnis just a convenience thing)

**Comment by afollestad** [comment]
Added in https://github.com/afollestad/app-theme-engine/commit/ffcd5fea3a39be8fd0bbe7a8c44f506dc856d16b
