### ISSUE TITLE
Apply of recreate

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#18]
So I have multiple activities that theme themselves based on a bitmap. Now, when the bitmap changes, I need to update colors (for example, status bar color and toolbar light mode based on customizer)

So, here is my question: does apply update everything, or do I need to recreate the activity

**Comment by afollestad** [comment]
`apply()` updates everything other than the Activity theme.

**Comment by afollestad** [comment]
It should automatically make a call to `preApply()` for you too, which applies status bar theming among other things.
