### ISSUE TITLE
TabLayout indicator color

### ISSUE THREAD

**Issue by julian200601** [afollestad/app-theme-engine#20]
`android:tag="tab_indicator_accent_color"` on `TabLayout` tints indicator black or white depending on the background but doesn't use the accent color. (For me and in the sample). Is this a Bug or did I miss something in the docs?

**Comment by afollestad** [comment]
It should work with version 0.5.1 now:

https://github.com/afollestad/app-theme-engine/releases/tag/0.5.1

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.6.0
