### ISSUE TITLE
Icons for Task Description

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#21]
Can you please add the ability to specify a custom icon to a task description? Either using the standard task description customizer or otherwise (preferably otherwise...)

Edit: Also titles please

**Comment by afollestad** [comment]
Added a field to the customizer; that's the most reliable way. Storing drawable resources is unreliable since resource IDs can change between builds.

Returning null for the method will fallback to the default (app's launcher icon).

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.6.0
