### ISSUE TITLE
Inconsistency among status bar and toolbar light modes?

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#26]
![screenshot_20160101-215344](https://cloud.githubusercontent.com/assets/11251606/12073015/af1f09e0-b0d2-11e5-9c04-87c1d392b75a.png)
Here is what I mean. To fix this you can get the darkness not from the primaryDark color, but the primary color.

(With customizers that will be harder to do but it would also be possible in some way, if, for example, the activity is both a toolbar and status bar customizer)

**Comment by afollestad** [comment]
It's better to be a bit more specific with issue titles, rather than one to two words, FYI.

Toolbar light mode is controlled with `lightToolbarMode`, which is also available through the toolbar customizer. I just didn't add a setting for that in the sample app.

**Comment by afollestad** [comment]
Unless I misunderstood what you meant.

**Comment by afollestad** [comment]
If the toolbar is considered dark, the status bar should be too since it's always a darker shade. Any other result is from user error.

**Comment by AnimbusDev** [comment]
Everything is set here on automatic @afollestad

And this works in reverse. If the toolbar is considered light, the status bar can be considered dark because it is a shade darker.

**Comment by afollestad** [comment]
Oh right, I see what you mean. 

Using primary dark color for toolbars could be a bit unintuitive for users of ATE, though.

**Comment by AnimbusDev** [comment]
@afollestad Right. I'm saying detect the dark state of the status bar from primary
Like so:
![screenshot_20160101-221933](https://cloud.githubusercontent.com/assets/11251606/12073067/d8745c52-b0d5-11e5-888e-50111da528fa.png)

**Comment by afollestad** [comment]
Oh, yeah, that's a good solution
