### ISSUE TITLE
Disabled colored states for tinted views

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#27]
More issues with preference views. When disabled, they do not indicate that whatsoever.

The dynamic page names here is disabled.
![screenshot_20160101-220713](https://cloud.githubusercontent.com/assets/11251606/12073035/0b17b71e-b0d4-11e5-928d-42350724edd6.png)

Same with some views. I have seen it with switches (not pictured here) and I'll assume it happens with the rest of the views.

**Comment by afollestad** [comment]
I'll have to add disabled states to selectors when I get the chance. 

I haven't seen issues with no images on switches, though. Make sure you're using SwitchCompat rather than Switch.

**Comment by AnimbusDev** [comment]
@afollestad I meant that I don't have an image with the switches acting up.

Sorry that I didn't clarify

**Comment by afollestad** [comment]
@AnimbusDev hmmm, I'm not able to reproduce disabled states for preferences not working. It works fine for me (see the latest code for the sample project, I made the dummy preference disabled).

Disabled states are needed elsewhere, obviously, but it works fine in preferences.

**Comment by afollestad** [comment]
Re-opening since I need to add disabled states for text/icons too (in TextViews and ImageViews/ImageButtons)

**Comment by afollestad** [comment]
Oops, I already added it for TextViews. I meant for Buttons and ImageButtons.
