### ISSUE TITLE
Selected NavigationView item background color for dark themes

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#28]
![screenshot_20160101-221448](https://cloud.githubusercontent.com/assets/11251606/12073050/299cb8c8-b0d5-11e5-83e2-ccf0812edce9.png)
This is still considered a light color by the code, so the drawer selected background is way too dark.

**Comment by afollestad** [comment]
The colors used there are based on the navigation view background color, I believe. 

That looks pretty normal to me. It follows the Material Design Guidelines for navigation drawers (well it's the inverted version of the light color which can only be used on light themed drawers).

**Comment by AnimbusDev** [comment]
@afollestad The color is way too dark.

Here is how it should look:
![screenshot_20160101-222339](https://cloud.githubusercontent.com/assets/11251606/12073081/525433e4-b0d6-11e5-814e-af9b31ed19a9.png)

And here I have it with my faithful (same color as shown in the md concept) theme and it works properly:
![screenshot_20160101-222456](https://cloud.githubusercontent.com/assets/11251606/12073084/80f76572-b0d6-11e5-86fc-dcbe3e160a93.png)

**Comment by AnimbusDev** [comment]
@afollestad The underlying issue here is that the background of the drawer is considered light enough to be light.
