### ISSUE TITLE
Toolbar Customizer breaks Collapsing toolbar support

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#34]
Returning a custom color using toolbar customizer still colors the toolbar even when collapsing toolbar layout is expanded

**Comment by afollestad** [comment]
Unable to reproduce.

It works fine in the sample project. The toolbar customizer doesn't affect how colors are applied, it just affects what colors are applied.

**Comment by AnimbusDev** [comment]
@afollestad Hmm...

Thats weird.
no clue why it is acting up like that
