### ISSUE TITLE
Issue with ATEToolbarCustomizer breaking collapsing toolbar is still present

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#36]
![screenshot_20160102-232904](https://cloud.githubusercontent.com/assets/11251606/12077247/a9f73f2e-b1a8-11e5-9d41-51ba7f33ea30.png)
Hmm. I don't know how to reproduce it...

I just use ATEToolbarcustonizer and ate status bar customizer.

**Comment by AnimbusDev** [comment]
@afollestad Here is the code

https://github.com/Substance-Project/GEM/blob/indev/mobile/src/main/java/com/animbus/music/ui/activity/albumDetails/AlbumDetails.java

**Comment by afollestad** [comment]
@AnimbusDev I was able to reproduce it in the sample project just now, but *only* when `setSupportActionBar()` is used to set a `Toolbar` as the support action bar. Without that, it works fine.

Looking into why that is now.

**Comment by afollestad** [comment]
@AnimbusDev oh I know why, it's because the background color is being set from `ATE.preApply()` *only* when `getSupportActionBar()` doesn't return null.

**Comment by AnimbusDev** [comment]
@afollestad This is great news!

Do you have an ETA for the next release?

**Comment by afollestad** [comment]
Fixed 😁

It should be released once this last issue is solved: https://github.com/afollestad/app-theme-engine/issues/25
