### ISSUE TITLE
Typeface tags

### ISSUE THREAD

**Issue by AlandEr2612** [afollestad/app-theme-engine#39]
Additional tags which allow you to set typefaces to text views would be nice.

Typeface caching should be used using maps, too.

**Comment by afollestad** [comment]
@AlandEr2612 updated the title and description.

**Comment by AlandEr2612** [comment]
Maybe something like... config.setTypeface (font in assets folder)

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.7.5

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/1.0.0
