### ISSUE TITLE
New toolbar customiser

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#43]
Can you please separate all of the toolbar methods into separate customisers? I do not see a use for returning the colors when you give me a toolbar, so please, separate it into this:

**ATEToolbarCustomizer**
* Light Mode
* Color

**ATEAdvancedToolbarCustomiser (extends are toolbar customiser**
* All methods from base
* Light mode with passing toolbar
* Color with passing toolbar

**Comment by AnimbusDev** [comment]
Oops didn't finish and posted

**Comment by afollestad** [comment]
You can just ignore the Toolbar parameter

**Comment by AnimbusDev** [comment]
@afollestad Right but there are now for methids, two of which I do not use.

**Comment by afollestad** [comment]
Having two very similar classes for the same thing would be redundant. It's still the same two methods as before, with added parameters.

**Comment by AnimbusDev** [comment]
@afollestad
Well, it looks like the new impl changed it. The older version (from two days ago) added redundant methods. Never mind then

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.7.5
