### ISSUE TITLE
Menu Theming and Collapsing Toolbar don't work together

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#47]
As the title says, the menu icon does not get themed until you collapse the CollapsingToolbarLayout.

**Comment by AnimbusDev** [comment]
@afollestad can you give an apk of the new sample? I have a feeling you misunderstood but cannot tell from the code.

**Comment by afollestad** [comment]
@AnimbusDev (GIF) 

![anglermmb29pafollestad01062016162710](https://cloud.githubusercontent.com/assets/1820165/12156805/c7f0f514-b492-11e5-9cf6-731d1d847d8e.gif)

**Comment by AnimbusDev** [comment]
@afollestad You misunderstood, but that still looks awesome.

Then, can you give us a way to disable that? For example, if the CollapsingToolbarLayout's text color is transparent, use the toolbar's light mode (with support for the toolbar customiser)

**Comment by afollestad** [comment]
@AnimbusDev there's no reliable way to do that, since the toolbar's background generally does not reflect the content that can be inside the expandable layout when it's expanded. The color has to be pulled from elsewhere.

**Comment by afollestad** [comment]
E.g. if you were pulling from album art that was only visible when the layout is expanded.

**Comment by AnimbusDev** [comment]
@afollestad 
Here is what I mean. An option to disable it. Otherwise use the toolbar light mode. Because now, my text is transparent (so it doesn't make the title be used twice) and it fades in as a scroll. The icons though, they would match the toolbar color (toolbar customiser sets color and light mode based on album art.) My issue was that if I set the toolbar to use light icons, the menu would stay dark until I collapsed the toolbar, updating it and theming the icon. So what I want is an option to use the old behaviour

**Comment by AnimbusDev** [comment]
@afollestad Thanks! One last thing, overall, if in any customiser, can you make it that returning 0 or null uses the default? If you don't need to use something you can return 0/null

**Comment by afollestad** [comment]
@AnimbusDev that's already done for task description icons, putting it everywhere else too is a good idea. Will do!

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.7.5
