### ISSUE TITLE
StatusBar Color Issue.

### ISSUE THREAD

**Issue by MidsizeMango** [afollestad/app-theme-engine#48]
Even when status bar color is set, it gets theme color. Like the example below.

![screenshot_20160106-204246 1](https://cloud.githubusercontent.com/assets/9977126/12146868/216d69e6-b4bc-11e5-83ab-e32c7ce63eaa.png)

And if I set my custom color like:

```java
@Override
    public int getStatusBarColor() {
        return note.getColor();
    }
```

...it crashes.

If I set `statusBarColor` programmatically, it doesn't apply the tinted color to it.

**Comment by afollestad** [comment]
I have no issues with this, I suspect your status bar color is getting overidden somewhere in your app.

The only way you could get a crash in `getStatusBarColor()` was if `note` is null.

**Comment by julian200601** [comment]
Could you post the post the error log?

**Comment by MidsizeMango** [comment]
@afollestad  but it is working perfectly fine for 
@Override
    public int getToolbarColor() {
        return note.getColor();
    }

**Comment by MidsizeMango** [comment]
@afollestad @julian200601 How can i set statusbar color programmatically with tint??

**Comment by afollestad** [comment]
@MidsizeMango `getStatusBarColor` is called by ATE before `onCreate()`, so your view isn't created yet.

**Comment by afollestad** [comment]
@MidsizeMango read the documentation.

```java
ATE.config(this, null)
    .statusBarColor(color)
    .commit();
```

or

```java
ATE.config(this, null)
    .statusBarColor(color)
    .apply(this);
```

**Comment by MidsizeMango** [comment]
@afollestad How can i set statusbar color programmatically with tint??

**Comment by afollestad** [comment]
@MidsizeMango the answer to your re-posted comment is above.

**Comment by MidsizeMango** [comment]
@afollestad Okay,Thanks.I will try.

**Comment by MidsizeMango** [comment]
@afollestad  StatusBarColor is applied.But no tint to StatusBar?

**Comment by afollestad** [comment]
@MidsizeMango there must be something not setup correctly in your app, you should read the documentation, and look at the sample project.

**Comment by MidsizeMango** [comment]
@afollestad Thanks for the library and help. Found a different solution.
