### ISSUE TITLE
Gradle Error with 0.3.1

### ISSUE THREAD

**Issue by jlelse** [afollestad/app-theme-engine#5]
JitPack seems to want a password to download the aar or to see the build log. What's up there? 0.2.1 worked well yesterday.

**Comment by afollestad** [comment]
Hmm, I haven't run into that issue. You may want to report it to JitPack's issue tracker.

**Comment by jlelse** [comment]
It says me "No subscription for github.com/afollestad"

**Comment by AlandEr2612** [comment]
I cant use the version 0.3.1 via gradle...

**Comment by jlelse** [comment]
Yes I wrote to Jitpack Support

**Comment by jlelse** [comment]
The problem seems to be solved by Jitpack or it is thanks to using a VPN

**Comment by afollestad** [comment]
It looks like JitPack is having more issues today unfortunately.

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.4.0
