### ISSUE TITLE
TabLayout text color issue

### ISSUE THREAD

**Issue by julian200601** [afollestad/app-theme-engine#59]
If you don't have any tab Text tags on a TabLayout,  isColorLight()  in TabLayoutProcessor isnt being checked, only if you have  "bg_primary_color" on the AppBarLayout, too. This ends up like this (sample):
![screenshot_20160111-025904](https://cloud.githubusercontent.com/assets/14248102/12225693/47d40afc-b810-11e5-8557-85d33c289f25.png)

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/1.0.0
