### ISSUE TITLE
View Tags can cause a ClassCastException

### ISSUE THREAD

**Issue by ccrama** [afollestad/app-theme-engine#6]
If you have a view with a custom tag (like a ViewHolder in a ListView) that is not a string, the method
```processTag()``` in ```ATE.java``` will cause a ClassCastException.

[Link to the line.](https://github.com/afollestad/app-theme-engine/blob/master/library/src/main/java/com/afollestad/appthemeengine/ATE.java#L138)

I don't know of a way you can really fix the issue except for warn developers not to use non-string tags, or maybe check if the tag is an instanceof String.

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.4.0

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/1.0.0
