### ISSUE TITLE
Navigation Drawer Tinting Mistake

### ISSUE THREAD

**Issue by Jawnnypoo** [afollestad/app-theme-engine#61]
It seems as though the navigation view selected color state is following the themes accent color, but according to the material guidelines, it should be the themes primary color, matching the toolbar:
https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-content

I know it is kinda nitpicky, I just wanted to see if you had done this intentionally.

**Comment by AnimbusDev** [comment]
@afollestad Can you please revert this? Most people use accent, so you are making a majority do more work (config, change the accent color, commit, config, change the navigation view to the recently applied accent color, apply).

One person that uses primary, they can do all that

**Comment by afollestad** [comment]
@AnimbusDev no, I'd prefer using Material Design Guidelines values as default.

You can set the accent color in your default configuration if you want to use that.

**Comment by AnimbusDev** [comment]
@afollestad Right, but every time you set the accent color you need to change, then commit, then change again, then apply (that's why I suggested the like attr thing, so when commuting it takes the value of accent)

**Comment by afollestad** [comment]
@AnimbusDev why would you need to do that?

You set it the first time your app launches. The theme engine doesn't apply until `onStart()` (after `onCreate()` is executed).

**Comment by afollestad** [comment]
Configuration upgrades are also possible using the variation of `isConfigured()` that takes an integer, if there are already previous defaults setup.

**Comment by kabouzeid** [comment]
I agree with Aidan (afollestad) here, Material Design Guidelines should be the default.
