### ISSUE TITLE
Not Processing AppBarLayout

### ISSUE THREAD

**Issue by Jawnnypoo** [afollestad/app-theme-engine#62]
It seems as though normal AppBarLayouts are not processed and are only being processed if the toolbar is a collapsing toolbar. I am using an AppBarLayout to hold a toolbar along with a TabLayout, and AppBarLayout is not being processed. Or possibly the TabLayout is not getting processed. Looks a little something like this:

![screenshot_2016-01-10-21-09-49](https://cloud.githubusercontent.com/assets/1459320/12227275/57b3e800-b7ef-11e5-984e-412d1764e54d.png)

I'll see if I can find something more useful out for you as to what is going on.

**Comment by Jawnnypoo** [comment]
And you can find the layout xml here if it is of any help:
https://gitlab.com/Commit451/GitLabAndroid/blob/master/app/src/main/res/layout/activity_project.xml

**Comment by afollestad** [comment]
Why exactly are you using `AppBarLayout` there? It has no use, your layout would look the same if you took the `AppBarLayout` out, since you're not using a `CoordinatorLayout`.

You should set a background tag to the TabLayout like the sample project does.

**Comment by AnimbusDev** [comment]
@afollestad AppBarLayout adds a proper toolbar shadow (even pre LP)

**Comment by afollestad** [comment]
@AnimbusDev good to know! I might have to use that in some of my apps.

I've added support for it anyways with the commit that closed this issue.

**Comment by Jawnnypoo** [comment]
Yes, the shadow is the reason I was using it. Thanks for the quick fix!

**Comment by julian200601** [comment]
@Jawnnypoo  you can use app:elevation="" , which provides backwards compatibility, too.

**Comment by Jawnnypoo** [comment]
@julian200601 on the Toolbar widget? Did not know that, thanks!

**Comment by julian200601** [comment]
@Jawnnypoo on any view

**Comment by Jawnnypoo** [comment]
Hmmm. I don't think that is quite true. Maybe it would work on 5.0+ and do nothing on the rest

**Comment by julian200601** [comment]
@Jawnnypoo you can believe me :)

**Comment by afollestad** [comment]
Yeah I'm pretty sure `app:elevation` just avoids the Lint warning, but doesn't actually do anything pre-Lollipop 😉

**Comment by julian200601** [comment]
@afollestad  really? Wouldn't FloatingActionButton not have a shadow below lollipop then, too?

**Comment by AnimbusDev** [comment]
@jullian200601 it uses the same thing as appbar layout. ViewCompat.setElevation()

**Comment by julian200601** [comment]
@AnimbusDev but how does it have elevation pre-L?

**Comment by AnimbusDev** [comment]
@julian200601 It draws out the shadow an alternative way using padding and such. Then it renders a gradient based on the float you give for the elevation

**Comment by julian200601** [comment]
@AnimbusDev didn't know that, thanks!
