### ISSUE TITLE
Solution to #61, Kinda @attr/ for ATE

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#63]
Can you give us a way to return something like ATE.ACCENT or ATE.PRIMARY to use the value from the ATE accent/ATE primary respectively?

In #61's case, it could be used in the case where, when setting the drawer selected text/icon using ATE.config(), you can pass ATE.PRIMARY and it will use the PRIMARY color. This could reduce the number of tags in some cases

**Comment by afollestad** [comment]
There are already static methods in `Config` used for value retrieval.

**Comment by julian200601** [comment]
@AnimbusDev  You can retrieve config values as @afollestad wrote like:
Config.primaryColor(Context context, String key); //returns the current primary color from the key's configuration
