### ISSUE TITLE
Switching from Recents back to Application messes up Toolbar

### ISSUE THREAD

**Issue by PDDStudio** [afollestad/app-theme-engine#7]
When Switching from Recents (or locking the phone while using an App which implements app-theme-engine) back into the application the toolbar starts stucking and disappears half above the statusbar.

**Comment by afollestad** [comment]
Oddly enough, this had been happening in the Settings Screen in the sample app too. Not really sure what the cause was, but using `android:fitsSystemWindows="true"` on the root layout of the Activity fixes it.

**Comment by afollestad** [comment]
Does this still happen?

**Comment by PDDStudio** [comment]
I'll check it out when I'm back on my computer and report then. btw, thanks for fixing the EdgeColor @afollestadt

**Comment by PDDStudio** [comment]
Just saw that I'm already using `android:fitSystemWindows="true"` (not only) on my root layout. (Which is a CoordinatorLayout) @afollestad

**Comment by afollestad** [comment]
Hmm, that might be the problem. I'll have to look into it more next week.

**Comment by PDDStudio** [comment]
It seems like the **CoordinatoLayout** is causing this problem, wrapping a simple RelativeLayout around it - fixes it (in my situation)

**Comment by afollestad** [comment]
I think I found the reason why, it was related to how `setSystemUiVisibility` was being used to apply dark status icons on Marshmallow.
