### ISSUE TITLE
Improve Toolbar processor

### ISSUE THREAD

**Issue by TR4Android** [afollestad/app-theme-engine#72]
Currently there are two things that don't seem to be properly processed with the Toolbar:
- [x] Toolbar subtitle
- [x] Toolbar menu items that only have text

Here's a screenshot if it's of any help to you:
![20160125_175930](https://cloud.githubusercontent.com/assets/10142068/12557945/7c8d6a4e-c38d-11e5-84bb-1d8150b4ea62.png)

Thanks for the great work!

**Comment by afollestad** [comment]
Thanks for the feedback, it's all very helpful.

Also, I didn't know GitHub had a tasks function, that's awesome.

**Comment by TR4Android** [comment]
@afollestad Sure :smile: I'm sorry that I'm flooding you with issues now, but those just came up while migrating an app to your (very helpful) app theme engine.
The tasks even show up in the issue overview, I've come to love them.

*PS: Have you considered implementing a custom [`LayoutInflatorFactory`](http://developer.android.com/reference/android/support/v4/view/LayoutInflaterFactory.html). I think this could solve a few troubles and allow for easier integration (and maybe even better performance).*

**Comment by kabouzeid** [comment]
_Offtopic_
@TR4Android is this a GitHub app in the screenshot?

**Comment by TR4Android** [comment]
@kabouzeid No, it's the [LabCoat for GitLab](https://gitlab.com/Commit451/LabCoat) application I'm currently working on :smiley:

**Comment by afollestad** [comment]
Good idea with using a `LayoutInflaterFactory`, I have it completely integrated with the library now. Fixing a few minor bugs, and then I'll implement your requests.

**Comment by afollestad** [comment]
All the `LayoutInflaterFactory` code is now on GitHub.

I've added Toolbar subtitle tinting. For the MenuItem text color, that may have to come with this: https://github.com/afollestad/app-theme-engine/issues/75

**Comment by TR4Android** [comment]
@afollestad Cool, good to hear :thumbsup: Thanks for all the work you are putting into this!

**Comment by afollestad** [comment]
@TR4Android glad to be of help!

Using a inflater factory turned out to be a genius decision; I was able to remove tons of code that was used for theming menu icons and overflows since all of those views get intercepted along the way.

**Comment by afollestad** [comment]
Wow, it even intercepts views in dialogs. This is crazy.

**Comment by afollestad** [comment]
Both of the original tasks of this issue are done and pushed.

**Comment by TR4Android** [comment]
@afollestad I'm glad I could be of help as well :smiley:

**Comment by afollestad** [comment]
I had to change the logic for the text-only menu items. It's not safe to set their text color since there's a chance they could go into the overflow menu and have a background different than the toolbar.
