### ISSUE TITLE
Improve TextView/EditText theming

### ISSUE THREAD

**Issue by TR4Android** [afollestad/app-theme-engine#73]
I'm currently lacking two customization tags for my EditText:
- [ ] Tag that tints the EditText line in its base state 
- [x] Tag that sets the hint text color (e.g. `text_hint_primary_dependent`)

Here are two screenshots (the first showing the EditText in its base state, the second after entering text):
![20160125_184204](https://cloud.githubusercontent.com/assets/10142068/12559118/6dd305ee-c393-11e5-9f29-31de742cf5ec.png)
![20160125_184107](https://cloud.githubusercontent.com/assets/10142068/12559121/7547a500-c393-11e5-8796-25a01a54b466.png)

The expected base state would have a (muted) white text color and a white line.

**Comment by Jawnnypoo** [comment]
I was wondering why this app looked familiar :wink:

**Comment by afollestad** [comment]
Regarding a tag for the underline, I tried to some different ways of doing that and none of them are too reliable since they would rely on other tags also being present.

The best solution I've come up with is to determine whether or not a dark/light base line should be used based on the immediate view background or parent view background, falling back to the window background if those are both null.

So in this case, the EditText would be inside of a purple view, and ATE would see that.

**Comment by afollestad** [comment]
The behavior above won't fully work until https://github.com/afollestad/app-theme-engine/issues/79 is done.

**Comment by TR4Android** [comment]
@afollestad Just checked with the current code, but the baseline is still not properly colored. Any special tag I need to apply?

**Comment by afollestad** [comment]
@TR4Android you need to use the `parent_dependent` tag in order for it to work in the case above. 

This is what it looks like in action in the sample project (under "Misc" in the nav drawer):

![screener_20160201 14-36-42](https://cloud.githubusercontent.com/assets/1820165/12730366/4a10bf6c-c8f1-11e5-84a8-21ef68a79be3.png)

It sees the darker background of its parent. This should also work with your toolbar background, or whatever the toolbar is inside of.

**Comment by TR4Android** [comment]
@afollestad Oops, I could have just checked the sample code, how embarrassing. Thanks a lot!

**Comment by afollestad** [comment]
You're welcome!

**Comment by TR4Android** [comment]
@afollestad Ok, everything seems to be working fine after migrating to the latest `master` version, but I would prefer it if the focused state of the `parent_dependent` tag would still be the accent color. Could you maybe switch the current behaviour or add a new tag? That would be awesome!

**Comment by TR4Android** [comment]
Also, `AutoCompleteTextView` and `AppCompatAutoCompleteTextView` don't seem to be properly supported yet. This should be easy though as it's basically just the same code as `EditText` (including the `TextInputLayout` handling).
