### ISSUE TITLE
Support for (AppCompat)Spinner

### ISSUE THREAD

**Issue by TR4Android** [afollestad/app-theme-engine#74]
The title pretty much says it, I'm lacking support for the `AppCompatSpinner` in my `Toolbar` which leads to the following:

![20160125_190523](https://cloud.githubusercontent.com/assets/10142068/12559658/a4f9447c-c396-11e5-886d-81d88124622f.png)

It should probably reuse the `text_???` tags and also apply the color to the dropdown triangle.

**Comment by afollestad** [comment]
I can add support for the dropdown arrow, but generally you'll need to apply theming to views in the adapter the spinner item text.

**Comment by TR4Android** [comment]
@afollestad Yes, that is correct. I can't think of any way to apply those to the standard list item, so I'd just be happy with the dropdown arrow :+1:

**Comment by afollestad** [comment]
I think this will require another new tag, which will be useful anyways.

Something like `tint_background_parent_dependent`, which will see the background color of the parent view and tint black or white accordingly. Also a primary dependent tag for this.

**Comment by afollestad** [comment]
I should note, you can just add a `text_primary_inverse` tag to your Spinner item layouts and it will work without any changes to your adapter. At least with the new inflater factory stuff.

**Comment by TR4Android** [comment]
@afollestad Now that you're restructuring a large part of the library might be a good time to review all the tags. I find a few of their names confusing (such as the similiarity of `text_primary_dependent` and `text_primary_color_dependent`). Might I suggest a new way that more closely resembles what the tags actually do:
The general structure of a tag would be `field|value` which can be still be divided with commas. So we'd have tags such as those: `text_color|primary_color_dependent` or `background|secondary_text_color_dependent` or `background|accent_color` etc. I think it would be clearer that way what the tags achieve. Just my thoughts after integration, thanks for your work!

**Comment by afollestad** [comment]
Good idea! Thanks

**Comment by afollestad** [comment]
I've added the new tag system, which uses extensible tag processors similar to the view processors. 

I've also added support for Spinners, along with many other view types that weren't supported before.

**Comment by TR4Android** [comment]
@afollestad Awesome! Thanks.

**Comment by afollestad** [comment]
All the changes for this release should be done!

It just needs testing now, and I gotta re-write the README.

**Comment by TR4Android** [comment]
Cool, I'll help with testing as soon as I can.

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/1.0.0
