### ISSUE TITLE
Theme edge color of RecyclerViews, ListViews, and ScrollViews

### ISSUE THREAD

**Issue by PDDStudio** [afollestad/app-theme-engine#8]
When using RecyclerView or ViewPager the EdgeColors won't apply after changing the Theme via ATE.

**Comment by afollestad** [comment]
Not 100% clear on what you mean.

You need to use `ATE.apply()` inside your RecyclerView adapter, and inside your ViewPager Fragments, if you don't do that now.

**Comment by AnimbusDev** [comment]
@afollestad He means the glow animation. When you scroll to the bottom of a list

**Comment by afollestad** [comment]
Ohh, right. Not sure if there's a way to theme that at runtime or not.

**Comment by plusCubed** [comment]
Reflection seems like the most probable way: http://stackoverflow.com/questions/27342957/how-to-change-the-color-of-overscroll-edge-and-overscroll-glow

**Comment by afollestad** [comment]
@plusCubed that's helpful, thanks!

Hopefully field names are the same for RecyclerView, since it doesn't inherit ScrollView.

**Comment by AnimbusDev** [comment]
@afollestad They are. Browsed source of recycler

**Comment by afollestad** [comment]
@AnimbusDev they're not, they have different names

**Comment by afollestad** [comment]
And also a different class type.

**Comment by afollestad** [comment]
It's a little more complex than I thought. The 4 `EdgeEffectCompat` instances in `RecyclerView` aren't initialized right away. It looks like they might not be initialized until the first time they're actually needed.

A work around might be to programmatically instantiate them right away.

**Comment by afollestad** [comment]
Using the scroll listener will probably work as mentioned here: http://stackoverflow.com/a/29469396/309644

**Comment by afollestad** [comment]
Done

**Comment by AnimbusDev** [comment]
@afollestad I guess they changed it

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.4.0
