### ISSUE TITLE
Final issue before a release: CollapsingToolbarLayout issues

### ISSUE THREAD

**Issue by afollestad** [afollestad/app-theme-engine#82]
See the sample project.

When scrolling, the navigation bar icon, action bar icons, and overflow icons should change in color to match the color of the expanding title.

I did some logging, and the code that changes color is executed. For some reason the changes aren't seen visually.

**Comment by AnimbusDev** [comment]
@afollestad Can you build the sample and give an apk? I am currently living without functional computers

**Comment by afollestad** [comment]
This is the last thing before a release now.

Any ideas, @kabouzeid?

**Comment by kabouzeid** [comment]
@afollestad I'll look into that now, maybe I'll be lucky.

**Comment by kabouzeid** [comment]
I think I've found the bug, give me some more time to fix it :)

**Comment by afollestad** [comment]
The issues still seem to be there unfortunately

**Comment by afollestad** [comment]
It's not always the same problem either, it's pretty random actually.

Sometimes the navigation icon, action buttons, and overflow button don't get updated. Not all of them are always affected either.

**Comment by kabouzeid** [comment]
Weird, it's working 100% of the time for me. Have you tried uninstalling the app and then reinstalling. Instant run sometimes mess with my builds.

**Comment by julianostarek** [comment]
@kabouzeid Could you just share an apk? I'm currently unable to build it myself...

**Comment by afollestad** [comment]
Odd, now it works. 

Thanks!

**Comment by afollestad** [comment]
Just have to type up the new documentation after I eat, and the release will go live.

**Comment by julianostarek** [comment]
Nice!

**Comment by kabouzeid** [comment]
@julianostarek were you able to compile now?

**Comment by julianostarek** [comment]
@kabouzeid No problem with that, there's currently no PC around me:)

**Comment by AnimbusDev** [comment]
@kabouzeid Can you still compile? I don't have a single computer around me for the next few days (dang banks and their processing donations) so I cannot compile myself
