### ISSUE TITLE
CollapsingToolbarLayout parallax not working

### ISSUE THREAD

**Issue by PDDStudio** [afollestad/app-theme-engine#83]
When using CollapsingToolbarLayout and an ImageView inside it, the parallax effect doesn't work anymore. Setting `android:tag="ate_ignore"` at the CollapsingToolbarLayout the parallax effect is working again but the colors aren't changed anymore (ofc this is obviously because of the ignore tag, but this is how I was able to check where this bug comes from)

**Comment by afollestad** [comment]
Duplicate of an open issue 

Btw, embrace yourself for the upcoming release. The entire library is restructured and uses a different method of applying.

**Comment by PDDStudio** [comment]
@afollestad I saw the open issue but as because it's not the complete same kind of bug I decided to open a new one. Thanks anyways, is there an ETA for the new version yet?

**Comment by afollestad** [comment]
Whenever that other issue is solved 😉

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/1.0.0
