### ISSUE TITLE
Leaking Activities

### ISSUE THREAD

**Issue by Jawnnypoo** [afollestad/app-theme-engine#84]
Hey there, 

Working on using app-theme-engine in [LabCoat](https://gitlab.com/Commit451/LabCoat). Right now, in our debug builds, we are using [LeakCanary](https://github.com/square/leakcanary), and we are getting leaks in almost every activity right now. 
![capture](https://cloud.githubusercontent.com/assets/1459320/12771978/1a936b6a-c9f3-11e5-95c2-fac4396b7a0a.PNG)
All of the tracked leaks so far look like this. Holding onto views in a static arraylist is surely a way to cause activity leaks. I would say the best ways to control this is either make the arraylist not static somehow, or to require the activities to have some sort of `ATE.onDestroy()` call or something which would be called when the activity calls `onDestroy` which would clear out those views.

Whatever you choose to do, I would recommend putting LeakCanary in the sample app to assure this kind of stuff is resolved. Let me know if you need anything clarified

**Comment by afollestad** [comment]
Good catch, thanks
