### ISSUE TITLE
Use code generation instead of subclassing

### ISSUE THREAD

**Issue by Jawnnypoo** [afollestad/app-theme-engine#85]
This is a very general issue, but I wanted to make a suggestion. This library relies on the end user subclassing an activity in order to get the theming. Have you considered looking into a system similar to [butterknife](https://github.com/JakeWharton/butterknife) for performing the theming? I think that code generation would greatly improve this library, making it more efficient in many ways. Similar to @Bind(R.id.viewId) you could annotate views with something like @Color("colorAccent") or whatever key you want to use, and ATE would go through and color those views the way it knows how. This would give opt in or out control using annotations which would generate code, making it much faster and allowing things to be checked at compile time instead of runtime. I do not know too much about code generation, but I have a suspicion that it would benefit this library a lot performance-wise

**Comment by afollestad** [comment]
I'm not sure if you're up to date with how the non published version of this library works or not. But the next release won't loop over existing views, it will catch them during inflation. So this issue won't really apply.

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/1.0.0

**Comment by Jawnnypoo** [comment]
Ahhh nice. Congrats on the 1.0, looking forward to diving in and taking a look
