### ISSUE TITLE
Add docs for creating a ViewProcessor

### ISSUE THREAD

**Issue by Jawnnypoo** [afollestad/app-theme-engine#86]
It seems really cool that you are able to register your own ViewProcessors in ATE. Seems very similar to cases like Gson where you need to register a custom deserializer for certain classes. It would be great to have an example either in the README or the sample on how to create a ViewProcessor so that people understand that they can solve the problem of a view not getting tinted properly themselves. Otherwise, there will be thousands of pull requests adding libraries just so that one view will get tinted properly. I think it makes sense that ATE would only be responsible for having the ViewProcessors related to the Android SDK and the support libraries, and have it well documented how users could create their own.

**Comment by afollestad** [comment]
I'll be rewriting the entire documentation soon since the next release is so different. 

There will also be tag processors.
