### ISSUE TITLE
R.style values can CHANGE when new resources are added.

### ISSUE THREAD

**Issue by kabouzeid** [afollestad/app-theme-engine#87]
Currently the theme is stored as the integer of its R.style. . When the user adds new resources the ids can change. This will cause serious graphical artifacts or force closes. Just happened to me, so this is nothing just theoretical.

**Comment by afollestad** [comment]
Yeah, I've thought about possible solutions to this but don't have any good solutions yet.

**Comment by kabouzeid** [comment]
There are only two solutions I see

1. the theme have to be stored as a string and the user would have to register a decoder which receives the string later and returns the theme res.

2. Store the theme as a String like "R.style.mytheme". ATE could use some kind of reflection then to receive the theme. (I believe there are even framework classes to receive the name of a res and getting a res by its name. That would be perfect, as you could keep the current API)

**Comment by Jawnnypoo** [comment]
`getResources().getResourceName(R.style.whatever)` is what you are looking for

**Comment by kabouzeid** [comment]
Yeah, that sounds perfect :)

**Comment by kabouzeid** [comment]
The issue with the second solution however is that it isn't refactoring save.

**Comment by MFlisar** [comment]
Refactoring problem can be easily solved via proguard setup...

**Comment by afollestad** [comment]
The latest commit should do it, I haven't tested it yet though

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/1.0.0
