### ISSUE TITLE
Not working with AppCompat Views

### ISSUE THREAD

**Issue by julianostarek** [afollestad/app-theme-engine#89]
ClassCastException when using AppCompat Views. This isn't really an issue but should be noted in the docs.

**Comment by afollestad** [comment]
Which views specifically?

**Comment by julianostarek** [comment]
@afollestad Doesn't this not matter?🤔 You cannot cast for example an ATESeekbar to an AppCompatSeekbar.

**Comment by afollestad** [comment]
Oh I thought you meant casting them to the base views, e.g. a regular `SeekBar`. I'll make all the ATE views inherit from the AppCompat versions.

**Comment by afollestad** [comment]
Although a few of them already do, e.g. `ATESpinner`

**Comment by julianostarek** [comment]
Your effort with this project is just awesome!😂 @afollestad
