### ISSUE TITLE
Additional modifiers for selector tints and shadow tints

### ISSUE THREAD

**Issue by AlandEr2612** [afollestad/app-theme-engine#9]
Would be great if the color of the Floating action button change... and the shadow on the textviews too...

**Comment by afollestad** [comment]
Use background tints for floating action buttons.

By shadows, you mean elevations? You shouldn't need to change elevation with a theme engine.

**Comment by afollestad** [comment]
I'll actually have to add background tints, since you can currently only tint the image.

**Comment by AlandEr2612** [comment]
i mean the TextViews shadows... like this code...

<TextView
            android:id="@+id/tv_app_name"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:gravity="center"
            android:shadowColor="?android:attr/colorPrimary"
            android:shadowDx="2.5"
            android:shadowDy="2.5"
            android:shadowRadius="5"
            android:tag="text_accent_color"
            android:text="@string/app_name"
            android:textSize="75sp" />

if my text view have shadow, maybe one tag that could change the shadow color with a Theme Engine color...

**Comment by afollestad** [comment]
Added tag values for modifying TextView shadows. Added tag values for tinting background selectors.

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.4.0
