### ISSUE TITLE
Toolbar tinting

### ISSUE THREAD

**Issue by julianostarek** [afollestad/app-theme-engine#93]
For whatever reason, Toolbar navigation icon, menu icon and title tinting stopped working with 1.0. Not sure if that matters but it's not an appbar.

**Comment by MenosGrante** [comment]
Have the same bug with 1.0 version.

**Comment by bishwash72** [comment]
+1. facing same issue.

**Comment by jlelse** [comment]
+1 Please fix this asap, I want to release my app update!

**Comment by julianostarek** [comment]
Finally tried 1.0.1, still facing Toolbar & TabLayout text tinting issues but at least this is gone now
